// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARGOV9A1shQmQn1PevNAQtPpfO1ZgUms4',
    appId: '1:814660348733:web:eb6e861ec3a68a559d7354',
    messagingSenderId: '814660348733',
    projectId: 'kaltani-ms',
    authDomain: 'kaltani-ms.firebaseapp.com',
    storageBucket: 'kaltani-ms.appspot.com',
    measurementId: 'G-6ZDY8LTRZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUaU5DjM7jeCqc3blHLgbP3O2mIVDqoQ8',
    appId: '1:814660348733:android:f9a1c3a2f71643a09d7354',
    messagingSenderId: '814660348733',
    projectId: 'kaltani-ms',
    storageBucket: 'kaltani-ms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU-AiKCn3J2Ogx15VKAqO3gjfvk7xvAB0',
    appId: '1:814660348733:ios:f0c7b158b28847899d7354',
    messagingSenderId: '814660348733',
    projectId: 'kaltani-ms',
    storageBucket: 'kaltani-ms.appspot.com',
    iosClientId: '814660348733-atfi5jfmrprodnhrhskie9ci19dhm3l9.apps.googleusercontent.com',
    iosBundleId: 'com.enkwave.kaltanimis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU-AiKCn3J2Ogx15VKAqO3gjfvk7xvAB0',
    appId: '1:814660348733:ios:f0c7b158b28847899d7354',
    messagingSenderId: '814660348733',
    projectId: 'kaltani-ms',
    storageBucket: 'kaltani-ms.appspot.com',
    iosClientId: '814660348733-atfi5jfmrprodnhrhskie9ci19dhm3l9.apps.googleusercontent.com',
    iosBundleId: 'com.enkwave.kaltanimis',
  );
}
